# Generated by Django 3.2.4 on 2022-09-18 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_auto_20220918_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
