# Generated by Django 3.2.4 on 2022-09-18 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(default='covers/sample-image.jpg', height_field=300, upload_to='covers/'),
        ),
    ]
